--- 
- name: Ensure test_users are disabled
  community.general.ipa_user:
    name: "{{ test_user }}"
    state: enabled
    ipa_host: ""{{ ipa_host }}""
    ipa_user: "{{ ipa_user }}"
    ipa_pass: "{{ ipa_pass }}"
